### ISSUE TITLE
Wrong path in /etc/profile.d/oraclejdk.sh

### ISSUE THREAD

**Issue by Driky** [scaleway-community/scaleway-java#7]
Java isn't installed in /opt/java/jdk1.8.0_60 (maybe in an old version of the image it was).
So the file :  
https://github.com/scaleway-community/scaleway-java/blob/master/overlay/etc/profile.d/oraclejdk.sh
is not correct.

the install path seems to be : 
/usr/lib/jvm/java-8-oracle/

**Comment by moul** [comment]
Closed by #8
